from enum import Enum


class SeverityEffect(str, Enum):
    ADDITIONAL_SERVICE = "ADDITIONAL_SERVICE"
    DETOUR = "DETOUR"
    MODIFIED_SERVICE = "MODIFIED_SERVICE"
    NO_SERVICE = "NO_SERVICE"
    OTHER_EFFECT = "OTHER_EFFECT"
    REDUCED_SERVICE = "REDUCED_SERVICE"
    SIGNIFICANT_DELAYS = "SIGNIFICANT_DELAYS"
    STOP_MOVED = "STOP_MOVED"
    UNKNOWN_EFFECT = "UNKNOWN_EFFECT"

    def __str__(self) -> str:
        return str(self.value)
